server:
  port: 8881

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: ENC(C+qmRjVP+D7Nmr6d5j7nyQ==)
      database: ENC(8G/+hgYTq8ngqOflas4l0w==)
      auto-index-creation: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(tWGA5AwA7zfo1sZnICWevhAA2lgnZ4cuUlePoiOY2ArQwYvfhQZOH3+quVDme9HKbtCdtDIqkRH33i5QVWLXL8iWJioa89tu)
    username: ENC(SJ+4G8Ju8tZmohXqlWzdxA==)
    password: ENC(sXGEffanhDIwEMMmz3YgdQrOnYwxjfqn)
